### ISSUE TITLE
Github workflow failure

### ISSUE THREAD

**Issue by rgksugan** [tnmyk/remind-kindle#3]
Today, I didn't receive the email and the job had failed. I looked into the issue and had to manually update the `pnpm-lock.yaml` file. Not sure if this is the right approach and we are supposed to update the lock file once in a while.

` ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE  Cannot perform a frozen installation because the lockfile needs updates`

**Comment by tnmyk** [comment]
Thanks for letting me know. I'll make a fix and test asap
